name: Deploy Terraform
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      
      # Pulls the latest version of your code from the Github repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Installs Terraform on the Github runner  
      -name: Set up Terraform
       uses: hashicorp/setup-terraform@v3

      # configure your AWS OIDC access by using the credentials stored in Github secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::943169211906:role/Githubconnect
          role-session-name: githubworkflowsession
          audience: sts.amazonaws.com

      # Initialized terraform    
      - name: Initialize Terraform
        run: terraform init
        
      # Execute the terraform plan
      - name: Terraform Plan
        run: terraform plan
        
      # Deploys terraform changes  
      - name: Terraform Apply
        run: terrfaorm apply -auto-approve

      # Destroy terraform resources (uncomment lines below) 
      # - name: Terrafoem Destroy
          run: terraform destroy -auto-approve    
